# Note: You must restart bin/webpack-dev-server for changes to take effect

default: &default
  source_path: app/frontend
  source_entry_path: packs
  check_yarn_integrity: false
  webpack_compile_output: false

  # Reload manifest.json on all requests so we reload latest compiled packs
  cache_manifest: false

development:
  <<: *default
  compile: true

  # Verifies that versions and hashed value of the package contents in the project's package.json
  check_yarn_integrity: true

  # NOTE: 実際にはconfig/webpack/development.jsの設定値が利用されている。（こちらの設定はdev-serverが起動中かどうか確認する為に必要）
  dev_server:
    https: false
    host: localhost
    port: 3035
    public: localhost:3035
    hmr: false

test:
  <<: *default
  compile: true

  # Compile test packs to a separate directory
  public_output_path: packs-test

production:
  <<: *default

  # Production depends on precompilation of packs prior to booting for performance.
  compile: false

  # Cache manifest.json for performance
  cache_manifest: true
